# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 22:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mapgroups.models


class Migration(migrations.Migration):

    dependencies = [
        ('mapgroups', '0004_auto_20150430_1729'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='activitylog',
            managers=[
                ('recent', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='admin',
            field=models.BooleanField(default=False, help_text='If true, this message is only viewable by managers.'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='associated_user',
            field=models.ForeignKey(blank=True, help_text='The user this message is associated with, if any.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emailinvitation',
            name='to_address',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='mapgroup',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to=mapgroups.models.map_group_image_path, width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='mapgroup',
            name='is_open',
            field=models.BooleanField(default=False, help_text='If false, users must be invited or request to join this group'),
        ),
        migrations.AlterField(
            model_name='mapgroupmember',
            name='is_manager',
            field=models.BooleanField(default=False, help_text='If true, this user may perform admin actions on this group'),
        ),
    ]
