# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapgroups', '0005_auto_20170311_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredgroups',
            name='map_group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mapgroups.MapGroup'),
        ),
        migrations.AlterField(
            model_name='mapgroup',
            name='permission_group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
