# Generated by Django 2.2.3 on 2019-07-10 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mapgroups.models


class Migration(migrations.Migration):

    dependencies = [
        ('mapgroups', '0005_auto_20190510_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='admin',
            field=models.BooleanField(default=False, help_text='If true, this message is only viewable by managers.'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='associated_user',
            field=models.ForeignKey(blank=True, help_text='The user this message is associated with, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mapgroup',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to=mapgroups.models.map_group_image_path, width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='mapgroup',
            name='is_open',
            field=models.BooleanField(default=False, help_text='If false, users must be invited or request to join this group'),
        ),
        migrations.AlterField(
            model_name='mapgroupmember',
            name='is_manager',
            field=models.BooleanField(default=False, help_text='If true, this user may perform admin actions on this group'),
        ),
    ]
