# Generated by Django 2.2.24 on 2021-08-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapgroups', '0006_auto_20190710_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapgroupmember',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Banned', 'Banned')], default='Accepted', max_length=256),
        ),
    ]
